# Generated by Django 3.2.7 on 2021-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='deatil_view',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
