# Generated by Django 3.2.7 on 2021-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_deatil_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='deatil_view',
            new_name='detail_view',
        ),
    ]
